### ISSUE TITLE
IconBorder Issue

### ISSUE THREAD

**Issue by StormFX** [Jaliborc/Bagnon-Masque#3]
It seems that under certain conditions, Bagnon_Facade's `IconBorder:SetAlpha(0)` isn't being applied correctly. For example, if one reloads the UI, kills a mob, loots a gray or white item and then moves an uncommon or better item to that slot, the `IconBorder` is still in its default state. I'm not sure _why_ this occurring. I was able to fix it by using adding an additional method overwrite to Bagnon_Facade, like so:

```lua
-- Edited this line:
local NewItem, FreeItem, UpdateItem = Item.New, Item.Free, Item.Update

-- Added these lines:
function Item:Update()
	UpdateItem(self)
	self.IconBorder:SetAlpha(0)
end
```

**Comment by GreyFoxGer** [comment]
Doesen't fixed for me :(

**Comment by StormFX** [comment]
Copy the code you changed and put it in a [gist](https://gist.github.com/).

**Comment by GreyFoxGer** [comment]
https://gist.github.com/GreyFoxGer/d166e338531233742f121e1f496d0abe

**Comment by StormFX** [comment]
If you're using Bagnon_Facade, you need to edit it, too. That code only affects Combuctor_Masque.

**Comment by GreyFoxGer** [comment]
i don't use bagnon at all...

**Comment by StormFX** [comment]
You mentioned Bagnon in the issue you posted on _Masque_. The fix was made for Bagnon_Facade. I didn't test it on Combuctor because I don't use Combuctor and, like I've already mentioned, it's not an issue with _Masque_.

**Comment by GreyFoxGer** [comment]
I just tested it with Bagnon, same thing.

Same border appears:
https://imgur.com/a/Wqf0q58

After icon get switched it appears normal:
https://imgur.com/a/1N1B1XZ

If i click on the button:
https://imgur.com/a/QDwju8O

Should be like:
https://imgur.com/a/pyFEyuJ


So,it's not 100% fixed :(

**Comment by StormFX** [comment]
The first image is not the same issue you pointed out in the other report. What you're seeing there is most likely the default `NewItem` texture, which is the texture that appears over newly looted items and then disappears when you mouse over it. The skin doesn't seem to be applied to it, which is the fault of the skin.

The issue with the `Pushed` texture is caused by the same issue as the one affecting `IconBorder`, which seems to be related to inheritance from the parent "class".

I didn't say it was 100% fixed. I demonstrated a fix that got it working on my end. I can't account for factors other than what I experienced. I used the fix I posted and tested the same scenario as was discussed, in the same manner. With the fix, the issue was gone on my computer.

At this point, you'll probably have to wait until the author fixes it.

**Comment by Jaliborc** [comment]
Just fyi, I haven't read this issue yet, cause I'm dealing with some a big higher priority issues. Will try to look at it this week.

**Comment by StormFX** [comment]
No problem, J.

@GreyFoxGer: Try [this](https://gist.github.com/StormFX/f9de64de5d60197cb75451f9e81900e5). (Replace the contents of Bagnon_Facade.lua)

**Comment by GreyFoxGer** [comment]
@StormFX still the same problem :(

**Comment by StormFX** [comment]
Don't know what to tell you, then. It's working fine on my end.

**Comment by Jaliborc** [comment]
Oh wow, forgot about this. 5 years ago!
Implemented, lmao.
